export const FETCH_HISTORIES_START = "FETCH_HISTORIES_START";
export const FETCH_HISTORIES_SUCCESS = "FETCH_HISTORIES_SUCCESS";
export const FETCH_HISTORIES_FAIL = "FETCH_HISTORIES_FAIL";

export const FETCH_PLACES_START = "FETCH_PLACES_START";
export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS";
export const FETCH_PLACES_FAIL = "FETCH_PLACES_FAIL";

export const CREATE_PLACE_START = "CREATE_PLACE_START";
export const CREATE_PLACE_SUCCESS = "CREATE_PLACE_SUCCESS";
export const CREATE_PLACE_FAIL = "CREATE_PLACE_FAIL";

export const UPDATE_PLACE_START = "UPDATE_PLACE_START";
export const UPDATE_PLACE_SUCCESS = "UPDATE_PLACE_SUCCESS";
export const UPDATE_PLACE_FAIL = "UPDATE_PLACE_FAIL";

export const DELETE_PLACE_START = "DELETE_PLACE_START";
export const DELETE_PLACE_SUCCESS = "DELETE_PLACE_SUCCESS";
export const DELETE_PLACE_FAIL = "DELETE_PLACE_FAIL";

export const FETCH_ROOMS_START = "FETCH_ROOMS_START";
export const FETCH_ROOMS_SUCCESS = "FETCH_ROOMS_SUCCESS";
export const FETCH_ROOMS_FAIL = "FETCH_ROOMS_FAIL";

export const FETCH_ATTENDEES_START = "FETCH_ATTENDEES_START";
export const FETCH_ATTENDEES_SUCCESS = "FETCH_ATTENDEES_SUCCESS";
export const FETCH_ATTENDEES_FAIL = "FETCH_ATTENDEES_FAIL";

export const UPDATE_ATTENDEES_START = "UPDATE_ATTENDEES_START";
export const UPDATE_ATTENDEES_SUCCESS = "UPDATE_ATTENDEES_SUCCESS";
export const UPDATE_ATTENDEES_FAIL = "UPDATE_ATTENDEES_FAIL";

export const ADD_MEETING_ROOM_INFO = "ADD_MEETING_ROOM_INFO";
export const ADD_MEETING_DATE_INFO = "ADD_MEETING_DATE_INFO";
export const ADD_MEETING_DETAIL_INFO = "ADD_MEETING_DETAIL_INFO";

export const SCHEDULE_MEETING_START = "SCHEDULE_MEETING_START";
export const SCHEDULE_MEETING_SUCCESS = "SCHEDULE_MEETING_SUCCESS";
export const SCHEDULE_MEETING_FAIL = "SCHEDULE_MEETING_FAIL";

export const ADD_MEETING_ATTENDEE_START = "ADD_MEETING_ATTENDEE_START";
export const ADD_MEETING_ATTENDEE_SUCCESS = "ADD_MEETING_ATTENDEE_SUCCESS";
export const ADD_MEETING_ATTENDEE_FAIL = "ADD_MEETING_ATTENDEE_FAIL";

export const UPDATE_HISTORY_START = "UPDATE_HISTORY_START";
export const UPDATE_HISTORY_SUCCESS = "UPDATE_HISTORY_SUCCESS";
export const UPDATE_HISTORY_FAIL = "UPDATE_HISTORY_FAIL";

export const DELETE_HISTORY_START = "DELETE_HISTORY_START";
export const DELETE_HISTORY_SUCCESS = "DELETE_HISTORY_SUCCESS";
export const DELETE_HISTORY_FAIL = "DELETE_HISTORY_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
